name: CI

on: push
#   schedule:
#   - cron: 23 7 * * 1-5 #UTC!

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: get quote
      run: curl --silent -o quotes.json https://raw.githubusercontent.com/daviferreira/defprogramming.com/master/src/data/quotes.json
    - name: extract quote from json
      run: |
        jq '. as $quotes | now | tostring | split(".") | join("") | tonumber as $num | $quotes | length as $size | $quotes[$num % $size] as $quote | { "quote": $quote.body, "by": $quote.authors | join(", ") } | @text "\(.quote)\n\(.by)"' quotes.json > quote.txt
    - name: print quote
      run: cat quote.txt
    
    - name: Notify slack channel
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        curl --request POST \
        --url $SLACK_WEBHOOK_URL \
        --header 'content-type: application/json' \
        --data "{
        \"attachments\": [{
                          \"author_name\": \"InspiringBot\",
                          \"title\": \"Inspiring development quote of the day:\",
                          \"text\": \"$(cat quote.txt)\"
                        }]
        }"
